-- MySQL Script generated by MySQL Workbench
-- Thu Apr 18 11:20:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullName` VARCHAR(255) NOT NULL,
  `birthday` DATE NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `phone` CHAR(12) NOT NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doctors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullName` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `workExperience` YEAR NOT NULL,
  `phone` CHAR(12) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  UNIQUE INDEX `fullName_UNIQUE` (`fullName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicesReports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicesReports` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `services` VARCHAR(100) NOT NULL,
  `notes` VARCHAR(255) NOT NULL,
  `doctors_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reports_doctors1_idx` (`doctors_id` ASC) VISIBLE,
  CONSTRAINT `fk_reports_doctors1`
    FOREIGN KEY (`doctors_id`)
    REFERENCES `mydb`.`doctors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `requiredDocuments` VARCHAR(255) NOT NULL,
  `doctors_id` INT NOT NULL,
  `servicesReports_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_services_doctors1_idx` (`doctors_id` ASC) VISIBLE,
  INDEX `fk_services_servecesReports1_idx` (`servicesReports_id` ASC) VISIBLE,
  CONSTRAINT `fk_services_doctors1`
    FOREIGN KEY (`doctors_id`)
    REFERENCES `mydb`.`doctors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_services_servecesReports1`
    FOREIGN KEY (`servicesReports_id`)
    REFERENCES `mydb`.`servicesReports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `status` ENUM('Создан', 'В процессе', 'Завершен', 'Отменен') NOT NULL,
  `patients_id` INT NOT NULL,
  `services_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_patients_idx` (`patients_id` ASC) VISIBLE,
  INDEX `fk_orders_services1_idx` (`services_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_patients`
    FOREIGN KEY (`patients_id`)
    REFERENCES `mydb`.`patients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_services1`
    FOREIGN KEY (`services_id`)
    REFERENCES `mydb`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prosthetics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prosthetics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `manufacturer` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) UNSIGNED NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `orders_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prosthetics_orders1_idx` (`orders_id` ASC) VISIBLE,
  CONSTRAINT `fk_prosthetics_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `mydb`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`appointments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dateTime` DATETIME NOT NULL,
  `room` INT NOT NULL,
  `status` ENUM('Запись назначена', 'Запись подтверждена', 'Запись отменена', 'Прием завершен') NOT NULL,
  `patients_id` INT NOT NULL,
  `doctors_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_appointments_patients1_idx` (`patients_id` ASC) VISIBLE,
  INDEX `fk_appointments_doctors1_idx` (`doctors_id` ASC) VISIBLE,
  CONSTRAINT `fk_appointments_patients1`
    FOREIGN KEY (`patients_id`)
    REFERENCES `mydb`.`patients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointments_doctors1`
    FOREIGN KEY (`doctors_id`)
    REFERENCES `mydb`.`doctors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patientHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patientHistory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `condition` VARCHAR(45) NOT NULL,
  `patients_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_patientHistory_patients1_idx` (`patients_id` ASC) VISIBLE,
  CONSTRAINT `fk_patientHistory_patients1`
    FOREIGN KEY (`patients_id`)
    REFERENCES `mydb`.`patients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
